---
# tasks/main.yml

- name: ocStore | Cache | Enumerate cache files
  find:
    paths: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
    file_type: "any"
    patterns: "{{ item.patterns }}"
    use_regex: True
  with_flattened:
    - "{{ ocstore_cache_path }}"
  register: ocstore_cache_files
  when: ocstore_cache_clean is defined and ocstore_cache_clean == "yes"

- name: ocStore | Cache | Build rm command list
  set_fact:
    ocstore_rm_cmd: |
      {% for result in ocstore_cache_files.results %}
        {% for item in result.files %}
          rm -rf {{ item.path }};
        {% endfor %}
      {% endfor %}
  when: ocstore_cache_clean is defined and ocstore_cache_clean == "yes"

- name: ocStore | Cache | Ensure cache files and folders absent
  shell: "{{ ocstore_rm_cmd | regex_replace(';\\s+rm -rf ', ';rm -rf ') | trim }}"
  changed_when: false
  when: ocstore_cache_clean is defined and ocstore_cache_clean == "yes"
